- .drone.yml
> added drone yml file

- .drone.yml
>  updates to drone checkout logic

- nav2_lifecycle_manager/CMakeLists.txt
- nav2_lifecycle_manager/package.xml
- nav2_lifecycle_manager/src/main.cpp
> rm lifecycle manager events executor

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
@tonynajjar  did it before increasing from 1 second to 10 seconds, as it transpired from several daily system tests that 
even 10 seconds are not enough, leading to a failed test with nav2 initialization failure. I am increasing it from 10s to 20s, and I see this change as not affecting operations, but rather decreasing false negatives for daily system test reports.
> Increase timeout: waiting longer for action server to become available

- nav2_velocity_smoother/src/velocity_smoother.cpp
---
| Info | Fix for nav2_velocity_smoother|
---
Related deep_cv PR: https://github.com/logivations/deep_cv/pull/4793
* Added condition to fix an error when using sim time
---
> AMRNAV-3826 Fix for nav2_velocity_smoother

- nav2_collision_monitor/include/nav2_collision_monitor/pointcloud.hpp
- nav2_collision_monitor/src/pointcloud.cpp
---
| Info | Add dynamic parameters to nav2 collision monitor |
---
* Added dynamic configuring of the parameters pointcloud.max_height, pointcloud.min_height
Related PR: https://github.com/logivations/deep_cv/pull/4793
We need these parameters to be dynamicaly configurable in order to turn on/off the collision monior by setting the parameters to some unrealistic values like poincloud.min_height = 10. SetNodeParameters BT node is responsible for this
---
> AMRNAV-3826 Add dynamic parameters to nav2 collision monitor

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
* Added a flag to not send goal in BtActionNode
Signed-off-by: Owen Hooper <17ofh@queensu.ca>
* Fixed cpplint and uncrustify issues.
* Update nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp
Signed-off-by: Owen Hooper <17ofh@queensu.ca>
Co-authored-by: Steve Macenski <stevenmacenski@gmail.com>
(cherry picked from commit 8e7090b86410da52f0a3b0ea0244fe53f272aade)
---
---
---
> Add-flag-to-not-send-goal-in-BTactionnode

- nav2_collision_monitor/include/nav2_collision_monitor/collision_monitor_node.hpp
- nav2_collision_monitor/src/collision_monitor_node.cpp
> Add frequency as parameter

- nav2_behavior_tree/include/nav2_behavior_tree/bt_service_node.hpp
it is used in https://github.com/logivations/deep_cv/pull/5306
> BT service node: add option to succeed when sending request is not needed

- nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
- nav2_behavior_tree/src/behavior_tree_engine.cpp
Errors are not sent to rosout. Not sure why, but passing the logger fixes the problem.
> AMRNAV-4638 fix missing behavior tree logs

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/back_up_action.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/drive_on_heading_action.hpp
- nav2_behavior_tree/plugins/action/back_up_action.cpp
- nav2_behavior_tree/plugins/action/drive_on_heading_action.cpp
- nav2_behaviors/plugins/back_up.cpp
- nav2_behaviors/plugins/drive_on_heading.hpp
- nav2_msgs/action/BackUp.action
- nav2_msgs/action/DriveOnHeading.action
see https://lvserv01.logivations.com/browse/AMRNAV-1988
revert changes to backup and add this to drive_on_heading
> AMRNAV-1988 Migrate backup BT nodes to DriveOnHeading

- nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
- nav2_lifecycle_manager/src/lifecycle_manager.cpp
---
see https://lvserv01.logivations.com/browse/AMRNAV-4429
> Amrnav 4429 Nav2 diagnostics improvement

- nav2_collision_monitor/include/nav2_collision_monitor/polygon.hpp
- nav2_collision_monitor/src/polygon.cpp
Ticket https://lvserv01.logivations.com/browse/AMRNAV-4974
Related PR: https://github.com/logivations/deep_cv/pull/6136
> AMRNAV-4974 Dynamically set max point for collision monitor

- nav2_controller/src/controller_server.cpp
- nav2_core/include/nav2_core/controller.hpp
backport https://github.com/logivations/navigation2/pull/34
> BACKPORT Add controller reset

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/follow_path_action.hpp
In the interface type is bool, in the BT node its string. It blocks us from passing bool blackboard variables as an input here
> Fix free_goal_vel type

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/wait_action.hpp
- nav2_behavior_tree/plugins/action/wait_action.cpp
- nav2_behavior_tree/test/plugins/action/test_wait_action.cpp
- nav2_bt_navigator/behavior_trees/nav_to_pose_with_consistent_replanning_and_if_path_becomes_invalid.xml
- nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml
- nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml
- nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_goal_patience_and_recovery.xml
- nav2_bt_navigator/behavior_trees/navigate_w_recovery_and_replanning_only_if_path_becomes_invalid.xml
* change duration type from int to double
* change "1" to "1.0" as default wait_duration value
* modify wait_action tests
* fix
* change int values to double in trees
* add usage of Duration::from_seconds()
* fix build failing issue
* delete whitespace
---
| Ticket(s) this addresses   | [AMRNAV-5586](https://lvserv01.logivations.com/browse/AMRNAV-5586) |
| Primary OS tested on | Ubuntu |
---
Here is a link for a PR in ros-planning/nav2 https://github.com/ros-planning/navigation2/pull/3871
---
> Backport wait_action node from nav2

- nav2_collision_monitor/CMakeLists.txt
- nav2_collision_monitor/include/nav2_collision_monitor/collision_detector_node.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/collision_monitor_node.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/polygon_source.hpp
- nav2_collision_monitor/package.xml
- nav2_collision_monitor/src/collision_detector_node.cpp
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_collision_monitor/src/pointcloud.cpp
- nav2_collision_monitor/src/polygon.cpp
- nav2_collision_monitor/src/polygon_source.cpp
- nav2_collision_monitor/src/range.cpp
- nav2_collision_monitor/src/scan.cpp
- nav2_collision_monitor/test/collision_detector_node_test.cpp
- nav2_collision_monitor/test/collision_monitor_node_test.cpp
- nav2_collision_monitor/test/sources_test.cpp
- nav2_msgs/CMakeLists.txt
- nav2_msgs/msg/PolygonsArray.msg
- nav2_util/include/nav2_util/robot_utils.hpp
- nav2_util/src/robot_utils.cpp
These are two PRs still waiting to be merged but I'm mostly satisfied with them at this point so to accelerate we can merge this and get the last nitpicks later
More info:
https://github.com/ros-planning/navigation2/pull/3885
https://github.com/ros-planning/navigation2/pull/3879
> Add Polygon source + add collision points debugging marker

- nav2_collision_monitor/include/nav2_collision_monitor/pointcloud.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/polygon_source.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/range.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/scan.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/source.hpp
- nav2_collision_monitor/src/collision_detector_node.cpp
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_collision_monitor/src/pointcloud.cpp
- nav2_collision_monitor/src/polygon_source.cpp
- nav2_collision_monitor/src/range.cpp
- nav2_collision_monitor/src/scan.cpp
- nav2_collision_monitor/src/source.cpp
- nav2_collision_monitor/test/collision_monitor_node_test.cpp
---
| Ticket(s) this addresses   | https://github.com/ros-planning/navigation2/pull/3879, https://github.com/ros-planning/navigation2/pull/3880, https://lvserv01.logivations.com/browse/AMRNAV-6228|
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | gazebo sim |
---
Backports https://github.com/ros-planning/navigation2/pull/3879 and https://github.com/ros-planning/navigation2/pull/3880
Related deep_cv PR: https://github.com/logivations/deep_cv/pull/7252
> Backport: [Collision Monitor] Add a watchdog mechanism

- nav2_collision_monitor/include/nav2_collision_monitor/types.hpp
- nav2_collision_monitor/src/collision_monitor_node.cpp
---
| Ticket(s) this addresses   | [AMRNAV-6230](https://lvserv01.logivations.com/browse/AMRNAV-6230) |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | gazebo |
---
* When comparing velocity command with `min_vel_before_stop` compare with squared `min_vel_before_stop` instead, since the velocity command is also squared.
* Use `max(velocity command, min_vel_before_stop)` to project robot's movement to prevent slowly driving very close to the obstacle
* Fix comment
> AMRNAV-6230 Fix collision monitor min_vel_before_stop parameter

- nav2_collision_monitor/src/polygon.cpp
Disable logging of updated polygons for collision monitor which we update at 2hz.
see https://lvserv01.logivations.com/browse/AMRNAV-6400
> disable logging to prevent spam

- nav2_costmap_2d/include/nav2_costmap_2d/costmap_layer.hpp
- nav2_costmap_2d/plugins/obstacle_layer.cpp
- nav2_costmap_2d/src/costmap_layer.cpp
add option to use min value of costmaps. Useful to "subtract" a map from another map.
> add function updateWithMin

- nav2_collision_monitor/CMakeLists.txt
- nav2_collision_monitor/README.md
- nav2_collision_monitor/include/nav2_collision_monitor/collision_detector_node.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/collision_monitor_node.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/polygon.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/velocity_polygon.hpp
- nav2_collision_monitor/params/collision_monitor_params.yaml
- nav2_collision_monitor/src/collision_detector_node.cpp
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_collision_monitor/src/polygon.cpp
- nav2_collision_monitor/src/velocity_polygon.cpp
- nav2_collision_monitor/test/CMakeLists.txt
- nav2_collision_monitor/test/collision_monitor_node_test.cpp
- nav2_collision_monitor/test/polygons_test.cpp
- nav2_collision_monitor/test/velocity_polygons_test.cpp
- nav2_util/include/nav2_util/array_parser.hpp
- nav2_util/src/CMakeLists.txt
- nav2_util/src/array_parser.cpp
backport velocity polygons to our fork:
https://github.com/ros-navigation/navigation2/pull/3708/files
> Backport velocity polygons

- nav2_collision_monitor/include/nav2_collision_monitor/polygon.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/velocity_polygon.hpp
- nav2_collision_monitor/src/polygon.cpp
- nav2_collision_monitor/src/velocity_polygon.cpp
- nav2_collision_monitor/test/velocity_polygons_test.cpp
reason for change: added the ability to set certain parameters for each sub-polygons (for limit, slowdown and approach type of velocity polygons)
so now, for each sub-polygon we can specify the slowdown_ration parameter:
```yaml
VelocityPolygonStop:
type: "velocity_polygon"
action_type: "slowdown"
min_points: 6
visualize: True
enabled: True
polygon_pub_topic: "velocity_polygon_stop"
velocity_polygons: ["rotation", "translation_forward", "translation_backward", "stopped"]
holonomic: false
rotation:
points: "[[0.3, 0.3], [0.3, -0.3], [-0.3, -0.3], [-0.3, 0.3]]"
linear_min: 0.0
linear_max: 0.05
theta_min: -1.0
theta_max: 1.0
slowdown_ration: 0.4
translation_forward:
points: "[[0.35, 0.3], [0.35, -0.3], [-0.2, -0.3], [-0.2, 0.3]]"
linear_min: 0.0
linear_max: 1.0
theta_min: -1.0
theta_max: 1.0 …
```
> improve param read in velocity polygon

- nav2_behaviors/include/nav2_behaviors/timed_behavior.hpp
---
| Ticket(s) this addresses   | https://lvserv01.logivations.com/browse/AMRNAV-6708 |
| Primary OS tested on | (Ubuntu) |
| Robotic platform tested on | (gazebo simulation) |
---
Reason for change:
AMR7 placed a pallet not quite next to the pallet inside the bin leave between them too much space. We call DriveOnHeading, after 2s we fail because of Timeout msec="2000" and cancel it.
After that we run another DriveOnHeading which fails because we don`t wait until previous call DriveOnHeading stops and clear our new goal. This cause this issue.
Changes in this PR:
- first we check action_server_->is_preempt_requested() then action_server_->is_cancel_requested() in TimedBehavior
> AMRNAV-6708 AMR7 placing pallet

- nav2_collision_monitor/include/nav2_collision_monitor/collision_monitor_node.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/velocity_polygon.hpp
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_collision_monitor/src/velocity_polygon.cpp
- nav2_msgs/CMakeLists.txt
- nav2_msgs/msg/ActiveVelocityPolygons.msg
- nav2_msgs/msg/VelocityPolygonPair.msg
https://lvserv01.logivations.com/browse/AMRNAV-6877
add the option to specify steering_angle_min and steering_angle_max in collision monitor velocity polygons. If that is specified, it should be used instead of the thetas
> AMRNAV-6877: collision monitor steering angle

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/condition/goal_reached_condition.hpp
- nav2_behavior_tree/plugins/condition/goal_reached_condition.cpp
- nav2_behavior_tree/test/plugins/condition/test_goal_reached.cpp
| Info                  | Please fill out this column               |
| --------------------- | ----------------------------------------- |
| Platform tested on    | Gazebo |
| Related documentation |                                           |
| Ticket                |  https://lvserv01.logivations.com/browse/AMRNAV-6916        |
Reason for change:
There is often a tradeoff while reaching goals: We want the AMR to drive as close as it can to the goal, without oscillating close to it. The AMR can easily adjust its x-coordinate compared to the goal by driving forward or backwards.
However, it cannot drive sideways, so it cannot correct sideways error easily. Instead, then it has to drive forward, turn, and drive backwards again.
Thus: We want to split the checker to check directions …
> AMRNAV-6916 Goal checker: Check for x and y separately

- nav2_controller/include/nav2_controller/plugins/simple_goal_checker.hpp
- nav2_controller/plugins/simple_goal_checker.cpp
- nav2_controller/plugins/stopped_goal_checker.cpp
| Info                  | Please fill out this column               |
| --------------------- | ----------------------------------------- |
| Platform tested on    | Gazebo |
| Related documentation |                                           |
| Ticket                | https://lvserv01.logivations.com/browse/AMRNAV-6980     |
Reason for change:
Please adapt the goal checkers to also offer the (optional) check in x and y direction in goal frame. Please adapt both StoppedGoalChecker and SimpleGoalChecker.
Changes in this PR:
-  check in x and y direction
Result:
x and y are checked separately
> AMRNAV-6980: Adapt goal checkers for separate x and y checks

- nav2_collision_monitor/include/nav2_collision_monitor/circle.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/collision_monitor_node.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/polygon.hpp
- nav2_collision_monitor/src/circle.cpp
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_collision_monitor/src/polygon.cpp
---
| Platform tested on	| Webots / Gazebo / Simple Simulation / AMR |
| Related Documentation|  |
| Ticket |  |
---
This PR modifies the way `collision_points` are published to ensure they are only published when they stop the AMR from moving. If they do not cause the AMR to stop, no collision points are published.  
Previously, collision points were published continuously, even when they were not affecting the AMR’s movement. This caused unnecessary processing and potential confusion in data interpretation.  
* Updated the logic in `collision_monitor_node.cpp` to publish `collision_points` only when they stop the AMR.  
* Added `getPointsInside(const std::vector<Point> & points, std::vector<Point>& points_inside)` in …
> collision_points publish only on STOP

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/control/recovery_node.hpp
- nav2_behavior_tree/plugins/control/recovery_node.cpp
| Info                  | Please fill out this column               |
| --------------------- | ----------------------------------------- |
| Platform tested on    | Webots / Gazebo / Simple Simulation / AMR |
| Related documentation |                                           |
| Ticket                |  https://lvserv01.logivations.com/browse/AMRNAV-6977     |
Reason for change:
Use case: RecoveryNode is often used to try sth, and "clean up" if the try failed before retrying. 
Now, if the number_of_retries is exhausted, the recovery is not performed. 
Add some option "recover_before_failing". It should instead still run the recovery part, and then fail anyway.
Changes in this PR:
1) add recover_before_failing InputPort to RecoveryNode that is false by default
2) RecoveryNode do it's …
> AMRNAV-6977: Add option recover_before_failing to RecoveryNode

- nav2_costmap_2d/plugins/obstacle_layer.cpp
- nav2_costmap_2d/src/costmap_layer.cpp
see https://app.foxglove.dev/pixel-robotics/view?ds=foxglove-stream&ds.deviceName=amr14&ds.start=2025-06-16T12%3A10%3A26.722Z&ds.end=2025-06-16T12%3A19%3A24.780Z&org=pixel-robotics&layoutId=e5cb8122-746a-48be-ac62-197648797b11&time=2025-06-16T12%3A18%3A18.771220051Z
dynamic param was changed but it looks not applied
added log to debug whether parameter value was set properly
> Amrnav 7266 debug dynamic param change
