logivations/navigation2

- nav2_costmap_2d/CMakeLists.txt
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
- nav2_costmap_2d/package.xml
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_lifecycle_manager/src/lifecycle_manager.cpp
- nav2_util/CMakeLists.txt
- nav2_util/include/nav2_util/node_thread.hpp
- nav2_util/include/nav2_util/service_client.hpp
- nav2_util/include/nav2_util/simple_action_server.hpp
- nav2_util/package.xml
- nav2_util/src/CMakeLists.txt
- nav2_util/src/node_thread.cpp
revert events executor for node thread, there it causes trouble
> revert NodeThread events executor

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
Reset blackboard on goal completion
Required for: https://github.com/logivations/deep_cv/pull/5235
> AMRNAV-4244 Reset blackboard on goal completion

- nav2_costmap_2d/include/nav2_costmap_2d/obstacle_layer.hpp
- nav2_costmap_2d/plugins/obstacle_layer.cpp
* add option to reset map to no_information after each update made to master grid
> AMRNAV-4517: Costmap to ros bridge: Split obstacles to different layers & AMRNAV-4518 Configure global obstacle layer for lidar

- nav2_behavior_tree/include/nav2_behavior_tree/plugins/action/drive_on_heading_action.hpp
> AMRNAV-1988 Migrate backup BT nodes to DriveOnHeading

- nav2_behaviors/plugins/drive_on_heading.hpp
removed sign inverting for negative distance
> Fix driveonheading driving forward only

- nav2_behaviors/plugins/drive_on_heading.hpp
> fix drive_on_heading

- nav2_collision_monitor/include/nav2_collision_monitor/polygon.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/types.hpp
- nav2_collision_monitor/params/collision_monitor_params.yaml
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_collision_monitor/src/polygon.cpp
This makes the robot eventually stop if the output velocity is small enough (in the APPROACH method)
> Add Minimum velocity before stopping

- nav2_collision_monitor/src/polygon.cpp
> Add dynamic params

- nav2_collision_monitor/src/polygon.cpp
> Backport dyn param

- nav2_behaviors/CMakeLists.txt
- nav2_behaviors/package.xml
- nav2_behaviors/src/main.cpp
- nav2_controller/CMakeLists.txt
- nav2_controller/src/main.cpp
- nav2_planner/CMakeLists.txt
- nav2_planner/package.xml
- nav2_planner/src/main.cpp
See https://github.com/logivations/deep_cv/pull/6526 for description
> Revert "add events executor to main"

- nav2_behavior_tree/include/nav2_behavior_tree/behavior_tree_engine.hpp
- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
- nav2_behavior_tree/src/behavior_tree_engine.cpp
> Throttle BT tick rate warnings

- nav2_collision_monitor/src/collision_detector_node.cpp
- nav2_collision_monitor/src/polygon.cpp
- nav2_controller/src/controller_server.cpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_subscriber.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/static_layer.hpp
- nav2_costmap_2d/plugins/static_layer.cpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
- nav2_costmap_2d/src/costmap_subscriber.cpp
- nav2_planner/src/planner_server.cpp
> Backport: AMRNAV-6258 Use intra process communication

- nav2_collision_monitor/src/collision_monitor_node.cpp
---
| Ticket(s) this addresses   | https://lvserv01.logivations.com/browse/AMRNAV-6398 |
| Primary OS tested on | Ubuntu |
---
Bug introduced in https://github.com/logivations/navigation2/pull/57/files#r1490728546
Result: https://drive.google.com/file/d/1__KNH7vIi3cT-EUAwGanqLQnS9rubHO6/view?usp=sharing
> AMRNAV-6398 Collision monitor sudden stops

- nav2_costmap_2d/src/costmap_2d_publisher.cpp
Backports: https://github.com/logivations/navigation2/pull/67
> Backport: AMRNAV-6339 Enable IPC for serialized topics

- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_publisher.hpp
- nav2_costmap_2d/include/nav2_costmap_2d/costmap_2d_ros.hpp
- nav2_costmap_2d/src/costmap_2d_publisher.cpp
- nav2_costmap_2d/src/costmap_2d_ros.cpp
---
| Ticket(s) this addresses   | https://lvserv01.logivations.com/browse/AMRNAV-6557 |
| Primary OS tested on | (Ubuntu) |
| Robotic platform tested on | gazebo simulation |
---
* Added parameter float map_vis_z_ to Costmap2DROS and Costmap2DPublisher, so we can use it to set info.origin.position.z costmap using parameter in .yaml file. map_vis_z_ = 0.0 by default
*Minimum value  without flickering is -0.008 for global_costmap
> Amrnav 6557 fix flickering visualization

- nav2_controller/include/nav2_controller/plugins/pose_progress_checker.hpp
- nav2_core/include/nav2_core/behavior_tree_navigator.hpp
- nav2_costmap_2d/src/costmap_2d_publisher.cpp
> Support dynamic name bt navigator

- nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/pointcloud.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/polygon.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/source.hpp
- nav2_collision_monitor/params/collision_detector_params.yaml
- nav2_collision_monitor/params/collision_monitor_params.yaml
- nav2_collision_monitor/src/collision_detector_node.cpp
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_collision_monitor/src/pointcloud.cpp
- nav2_collision_monitor/src/polygon.cpp
- nav2_collision_monitor/src/range.cpp
- nav2_collision_monitor/src/scan.cpp
- nav2_collision_monitor/src/source.cpp
- nav2_collision_monitor/test/collision_monitor_node_test.cpp
- nav2_controller/include/nav2_controller/controller_server.hpp
- nav2_controller/include/nav2_controller/plugins/pose_progress_checker.hpp
- nav2_controller/include/nav2_controller/plugins/simple_progress_checker.hpp
- nav2_controller/plugins/pose_progress_checker.cpp
- nav2_controller/plugins/simple_progress_checker.cpp
- nav2_controller/src/controller_server.cpp
- nav2_core/include/nav2_core/behavior_tree_navigator.hpp
- nav2_core/include/nav2_core/controller.hpp
- nav2_core/include/nav2_core/progress_checker.hpp
- nav2_costmap_2d/src/costmap_2d_publisher.cpp
- nav2_dwb_controller/dwb_core/include/dwb_core/dwb_local_planner.hpp
- nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp
- nav2_util/include/nav2_util/node_utils.hpp
- nav2_util/include/nav2_util/simple_action_server.hpp
- nav2_util/src/node_utils.cpp
- nav2_velocity_smoother/src/velocity_smoother.cpp
> merge transient_local_publish into iron

- nav2_collision_monitor/CMakeLists.txt
- nav2_collision_monitor/README.md
- nav2_collision_monitor/include/nav2_collision_monitor/collision_detector_node.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/collision_monitor_node.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/polygon.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/velocity_polygon.hpp
- nav2_collision_monitor/params/collision_monitor_params.yaml
- nav2_collision_monitor/src/collision_detector_node.cpp
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_collision_monitor/src/polygon.cpp
- nav2_collision_monitor/src/velocity_polygon.cpp
- nav2_collision_monitor/test/CMakeLists.txt
- nav2_collision_monitor/test/collision_monitor_node_test.cpp
- nav2_collision_monitor/test/polygons_test.cpp
- nav2_collision_monitor/test/velocity_polygons_test.cpp
- nav2_util/include/nav2_util/array_parser.hpp
- nav2_util/src/CMakeLists.txt
- nav2_util/src/array_parser.cpp
backport of:
https://github.com/logivations/navigation2/pull/75
https://github.com/logivations/navigation2/pull/71
deep_cv part: https://github.com/logivations/deep_cv/pull/8266
> Backport collision monitor

- nav2_behavior_tree/src/behavior_tree_engine.cpp
we know that sometimes we miss a beat, no need to constantly remind us
> remove spammy BT tick rate warning

- nav2_velocity_smoother/include/nav2_velocity_smoother/velocity_smoother.hpp
- nav2_velocity_smoother/src/velocity_smoother.cpp
> Iron vel smoother bounded open loop

- nav2_collision_monitor/include/nav2_collision_monitor/collision_monitor_node.hpp
- nav2_collision_monitor/include/nav2_collision_monitor/velocity_polygon.hpp
- nav2_collision_monitor/src/collision_monitor_node.cpp
- nav2_collision_monitor/src/velocity_polygon.cpp
- nav2_msgs/CMakeLists.txt
- nav2_msgs/msg/ActiveVelocityPolygons.msg
- nav2_msgs/msg/VelocityPolygonPair.msg
> Collision monitor debugging

- nav2_behaviors/include/nav2_behaviors/timed_behavior.hpp
Somehow missed https://github.com/logivations/navigation2/pull/78/files
> Fix canceling issue backport

- nav2_planner/include/nav2_planner/planner_server.hpp
- nav2_planner/src/planner_server.cpp
> Amrnav 7167 separate costmap for no-go areas

- nav2_controller/include/nav2_controller/controller_server.hpp
- nav2_controller/src/controller_server.cpp
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
https://github.com/logivations/deep_cv/pull/10064
> Extract global plan publishing to controller server

- nav2_controller/include/nav2_controller/controller_server.hpp
- nav2_controller/src/controller_server.cpp
- nav2_regulated_pure_pursuit_controller/include/nav2_regulated_pure_pursuit_controller/regulated_pure_pursuit_controller.hpp
- nav2_regulated_pure_pursuit_controller/src/regulated_pure_pursuit_controller.cpp
Reverts logivations/navigation2#99
> Revert "Extract global plan publishing to controller server"

- nav2_lifecycle_manager/include/nav2_lifecycle_manager/lifecycle_manager.hpp
- nav2_lifecycle_manager/src/lifecycle_manager.cpp
> lifecycle manager: launch nodes in parallel
